name: 'Build Java Gradle Action'
#
description: Build a Java repository using Gradle
inputs:
  java_version:
    description: The Java version to use
    required: true
  java_distribution:
    description: The Java distribution to use
    required: true
  gradle_version:
    description: The Gradle version to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ inputs.gradle_version }}
    - name: Execute Gradle build
      run: ./gradlew build -x test
      shell: bash
    - name: Bump version and push tag
      id: bumpTag2
      uses: anothrNick/github-tag-action@1.36.0
      env:
        # TODO Figure-out how to pass this in
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: true
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/libs/*.jar
          **/build/libs/*.jar
        tag_name: ${{ steps.bumpTag2.outputs.new_tag }}
        
